---

- name: Prepare OpenStack Helm host
  hosts: all
  vars:
    # openstack_release: ocata
    # container_distro_name: ubuntu
    # container_distro_version: xenial
    openstack_release: rocky
    container_distro_name: opensuse
    container_distro_version: '15'
  remote_user: ubuntu
  tasks:

    - name: Install additional packages
      become: yes
      apt:
        install_recommends: no
        update_cache: yes
        name:
          - bc
          - build-essential
          - ca-certificates
          - curl
          - git
          - jq
          - make
          - nmap
          - python-dev
          - python-pip
          - python-setuptools
          - uuid-runtime
      async: 1000
      poll: 0
      register: package_sleeper

    - name: Install sudoers file
      become: yes
      copy:
        dest: /etc/sudoers.d/50-root
        content: root ALL=(ALL) NOPASSWD:ALL
        owner: root
        group: root
        mode: '440'

    - name: Configure git name
      git_config:
        scope: global
        name: user.name
        value: 'Nicolas Bock'

    - name: Configure git email
      git_config:
        scope: global
        name: user.email
        value: 'nicolas.bock@suse.com'

    - name: Configure vim for user
      lineinfile:
        create: yes
        line: set background=dark
        path: "${HOME}/.vimrc"
        regexp: 'set (bg|background)='

    - name: Configure vim for root
      become: yes
      lineinfile:
        create: yes
        line: set background=dark
        path: "${HOME}/.vimrc"
        regexp: 'set (bg|background)='

    - name: Clone openstack-helm-infra
      git:
        dest: "${HOME}/openstack-helm-infra"
        repo: https://opendev.org/openstack/openstack-helm-infra.git
        force: yes

    - name: Clone openstack-helm
      git:
        dest: "${HOME}/openstack-helm"
        repo: https://opendev.org/openstack/openstack-helm.git
        force: yes

    - name: Set environment variables
      lineinfile:
        path: "${HOME}/.bashrc"
        regexp: "^[^#]{{ item.key }} *="
        line: "export {{ item.key }}={{ item.value }}"
      with_dict:
          - OPENSTACK_RELEASE: "{{ openstack_release }}"
          - CONTAINER_DISTRO_NAME: "{{ container_distro_name }}"
          - CONTAINER_DISTRO_VERSION: "{{ container_distro_version }}"
          - CLIFF_FIT_WIDTH: "1"
          - OS_CLOUD: openstack_helm

    - name: Copy deployment script
      template:
        src: deploy-osh-developer-environment.sh.j2
        dest: "${HOME}/deploy-osh-developer-environment.sh"
        mode: "0755"
        owner: ubuntu

    - name: Check status of package install
      become: yes
      async_status:
        jid: "{{ package_sleeper.ansible_job_id }}"
      register: package_result
      until: package_result.finished
      retries: 500
